[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.server"

[deploy]
startCommand = "python -m uvicorn src.server.main:socket_app --host 0.0.0.0 --port $PORT --workers 1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
